# Generated by Django 2.1.11 on 2020-01-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=128, verbose_name='Place ID')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('name', models.CharField(max_length=128, verbose_name='Place Name')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Place Description')),
                ('visited_date', models.CharField(max_length=128, null=True, verbose_name='Visited Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('user', 'place_id')},
        ),
    ]
